#!/bin/sh
# Handle by extension
case ${1##*.} in
    # Archive
    a|ace|alz|apk|arc|arj|bz|bz2|cab|cpio|deb|gz|iso|jar|lha|lz|lzh|lzma|lzo|\
    rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip|zst)
        bsdtar --list --file "$1" && exit ;;
    rar)
        unrar lt -p- -- "$1" && exit ;;
    7z)
        7z l -p -- "$1" && exit ;;

    # PDF
    pdf) # Convert pdf file to texts
		pdftoppm -jpeg -singlefile "$1" /tmp/lfthumb
		preview-image draw "/tmp/lfthumb.jpg" "$2" "$3" "$4" "$5" && exit 1 ;;

    # BitTorrent
    torrent)
        transmission-show -- "$1" && exit ;;

    # OpenDocument
    odt|ods|odp|sxw) # Preview as text conversion
        odt2txt "$1" && exit ;;

    # HTML
    htm|html|xhtml)
        # Preview as text conversion
        w3m -dump "$1" ||
        lynx -dump -- "$1" ||
        elinks -dump "$1" && exit ;;

    svg)
        convert -resize 200x200 "$1" /tmp/lfthumb.png
		preview-image draw "/tmp/lfthumb.png" "$2" "$3" "$4" "$5" && exit 1 ;;
    *) ;; # Go on to handle by mime type
esac

# Handle by mime types
case "$(file -Lb --mime-type -- "$1")" in
    # Text
    text/*|*/xml|*/csv|*/json)
        # try to detect the charactor encodeing
        enc=$(head -n20 "$1" | uchardet)
        head -n 100 "$1" |
        { if command -v highlight > /dev/null 2>&1; then
            highlight -O ansi --force
        else
            cat
        fi } |
        iconv -f "${enc:-UTF-8}" -t UTF-8 && exit ;;

    # Image
    image/*)
        preview-image draw "$1" "$2" "$3" "$4" "$5" && exit 1 ;;
	video/*)
		ffmpegthumbnailer -s 300 -i "$1" -o /tmp/lfthumb.jpg
		preview-image draw "/tmp/lfthumb.jpg" "$2" "$3" "$4" "$5" && exit 1 ;;
    # Video and audio
    audio/*|application/octet-stream)
        mediainfo "$1" && exit ;;

    *) ;; # Go on to fall back
esac

# None of above exits, this is the fall back
echo '----- File Type Classification -----'
file --dereference --brief -- "$1"
