#!/bin/sh

if xrandr | grep "HDMI-1 connected"
then
	eww open --screen eDP-1 bar
	eww open --screen HDMI-1 extrabar
	bspc monitor eDP-1 -d  1 2 3 4 5 6 7 
	bspc monitor HDMI-1 -d  8 9 0 
	bspc config focus_follows_pointer true
else
	eww open --screen eDP-1 bar
	bspc monitor eDP-1 -d  1 2 3 4 5 6 7 8 9 
	bspc config focus_follows_pointer true
fi;

bspc config top_padding 35

bspc config remove_unplugged_monitors	true
bspc config remove_disabled_monitors	true
